### ISSUE TITLE
A context manager for wrapping functions with retry functionality

### ISSUE THREAD

**Issue by GektorPrime** [str0zzapreti/pytest-retry#10]
Please add a context manager for wrapping functions with retry functionality similarly as implemented here: https://pypi.org/project/redo/

**Comment by str0zzapreti** [comment]
Closing this issue because this functionality is out of the scope of pytest-retry, which deals specifically with retrying Pytest test functions. If you need a context manager for retrying generic functions, I would suggest using another library or defining one yourself.
