### ISSUE TITLE
Support configuration through `pytest.ini` / `pyproject.toml`

### ISSUE THREAD

**Issue by amotl** [str0zzapreti/pytest-retry#23]
Dear Silas,

we just wanted to refer you to the conversation at https://github.com/earthobservations/wetterdienst/pull/1041#issuecomment-1745512644, where we outlined why we used `pytest-rerunfailures`, because we were fancying the possibility to configure it using `pytest.ini` / `pyproject.toml`.

Maybe this is a sensible feature you may want to add to the `pytest-retry` addon?

With kind regards,
Andreas.

**Comment by str0zzapreti** [comment]
I think this is a great suggestion, thanks for bringing it to my attention. I don't think it would be too hard to implement.

**Comment by str0zzapreti** [comment]
Created a PR: https://github.com/str0zzapreti/pytest-retry/pull/24
If you have time for a quick review I'd sure appreciate it! Either way I should have this released sometime tomorrow.

**Comment by str0zzapreti** [comment]
Released with [1.5.0](https://github.com/str0zzapreti/pytest-retry/releases/tag/1.5.0)!
